"""Request models for the write endpoints (spec.md FR2).

Validation mirrors the SQL CHECK constraints in
dataset/db/migrations/006_outputs.sql exactly, plus a constraint the SQL
doesn't carry but the ontology does: eat:cites is "1..n" on both eat:Score
and eat:RankedPlacement (every score and every ranked placement must cite at
least one evidence node) -- enforced here since Postgres has no way to. This
is also what backs spec.md NFR2 on the read side: a read endpoint can only
ever return evidence-free placements/scores if one somehow got written
without going through this validation.

Every field below carries a `description` (and, where the value's shape
isn't self-evident, an `examples`) -- these render in /docs (Swagger UI) so
an agent or UI developer reading the schema, not just this file, can tell
what each field is for.
"""

from __future__ import annotations

from datetime import date
from typing import Literal

from pydantic import BaseModel, Field, field_validator, model_validator

EvidenceType = Literal["observation", "condition", "triage_event", "bed_status", "clinic_session"]
CitationRole = Literal["urgency", "capacity", "timeframe", "multi_list"]
AgentName = Literal["urgency", "capacity"]
Sex = Literal["M", "F", "U"]


class ScoreCitationIn(BaseModel):
    """One piece of evidence an agent score cites. Becomes an `eat:cites`
    edge from the `Score` node to this evidence node in the graph."""

    evidence_type: EvidenceType = Field(
        description=(
            "Which evidence class this cites. Determines the IRI template "
            "`evidence_key` must match (see `evidence_key`'s own description)."
        ),
    )
    evidence_key: str = Field(
        description=(
            "The composite-key suffix from this evidence_type's own IRI template "
            "(conductor/kg/namespaces.md #4) -- NOT an opaque ID, and not "
            "generated by this service. The caller must supply it pre-formatted: "
            "'observation' -> '{hospital_hipe}/{pathway_number}/{obs_datetime}/"
            "{column}'; 'condition' -> '{hospital_hipe}/{pathway_number}/"
            "{icd10am_code}'; 'triage_event' -> just the triage_event_id; "
            "'bed_status' -> '{hospital_hipe}/{ward_id}/{snapshot_datetime}'; "
            "'clinic_session' -> '{hospital_hipe}/{clinic_code}/{session_date}'. "
            "Percent-encode characters that aren't IRI-safe (spaces/colons in a "
            "timestamp, e.g. '2026-08-16 09:16:00' -> "
            "'2026-08-16%2009%3A16%3A00')."
        ),
        examples=["9001/PW-9001-000007/2026-08-16%2009%3A16%3A00/hr"],
    )


class ScoreIn(BaseModel):
    """One urgency or capacity agent's score for one referral (spec.md FR2).
    Written to `agent.agent_scores`/`agent_citations`, then projected as an
    `eat:Score` node with `eat:cites` edges -- POST this once per referral
    per agent per run."""

    run_id: str = Field(
        description=(
            "Identifies this agent execution. Scopes the graph Activity this "
            "score is attributed to, and the `run/{run_id}` named graph it's "
            "projected into -- use the same run_id across every score and "
            "decision produced by one coordinator run."
        ),
        examples=["run-2026-09-04-001"],
    )
    agent_name: AgentName = Field(description="Which agent produced this score.")
    hospital_hipe: str = Field(
        min_length=4, max_length=4, description="4-character HIPE hospital code.", examples=["9001"]
    )
    pathway_number: str = Field(
        description="The referral's pathway number -- unique within the hospital, not globally.",
        examples=["PW-9001-000007"],
    )
    as_of_date: date = Field(description="The date this score was computed for.")
    score: float = Field(ge=0, le=1, description="The score itself, normalised to [0, 1].")
    method: str = Field(
        description=(
            "Free-text identifier for the scoring method/rubric used, e.g. "
            "'mts-news2-v1' -- for reproducibility, not machine-parsed."
        ),
    )
    agent_version: str = Field(
        description="Version string of the agent that produced this score -- for reproducibility."
    )
    citations: list[ScoreCitationIn] = Field(
        min_length=1,
        description=(
            "Evidence this score is based on. Must be non-empty -- `eat:cites` "
            "is 1..n on `eat:Score` in the ontology, so an unsupported score "
            "can't be written."
        ),
    )


class DecisionCitationIn(BaseModel):
    """One piece of evidence for one ranked position. Becomes an
    `eat:cites*` edge (a specific role subproperty, not the base
    `eat:cites`) from the `RankedPlacement` node to this evidence node."""

    evidence_type: EvidenceType = Field(description="See ScoreCitationIn.evidence_type.")
    evidence_key: str = Field(
        description="See ScoreCitationIn.evidence_key -- same format rules apply."
    )
    role: CitationRole = Field(
        description=(
            "Which of the four `eat:cites` subproperties this citation uses "
            "(urgency/capacity/timeframe/multi_list) -- this is what powers "
            "GET /evidence's role-scoped filtering and the clinician UI's "
            "per-section row expansion."
        ),
    )


class RuleCheckIn(BaseModel):
    """One CPC/CRT/ordering rule result for one ranked position."""

    rule_id: str = Field(
        description=(
            "Must be an existing rule_id in core.ref_rules (e.g. "
            "'RULE-CRT-URGENT', 'RULE-CRT-SEMI', 'RULE-TRIAGE-TURNAROUND', "
            "'RULE-ORDER', 'RULE-TIEBREAK') -- foreign-key enforced at the "
            "Postgres layer, so an unknown rule_id is rejected with 400, not "
            "422 (Pydantic has no way to check this without a DB round-trip)."
        ),
        examples=["RULE-CRT-URGENT"],
    )
    passed: bool = Field(description="Whether this referral's ranking satisfies the rule.")
    detail: str | None = Field(
        default=None,
        description=(
            "Optional free-text explanation, most useful when `passed` is "
            "false. Omit or use `null` -- never the literal string 'None'."
        ),
    )


class RankingIn(BaseModel):
    """One ranked position within a decision -- one referral's place in the
    list, with its own evidence and rule checks."""

    hospital_hipe: str = Field(
        min_length=4, max_length=4, description="4-character HIPE hospital code.", examples=["9001"]
    )
    pathway_number: str = Field(
        description="The ranked referral's pathway number.", examples=["PW-9001-000007"]
    )
    position: int = Field(
        gt=0,
        description=(
            "1-based rank position within this decision. Must be unique among "
            "all rankings in the same decision (checked below)."
        ),
    )
    triage_category: int | None = Field(
        default=None,
        description="Optional CPC/triage category code, if already known at ranking time.",
    )
    urgency_score: float = Field(
        ge=0,
        le=1,
        description=(
            "This referral's urgency score at ranking time, denormalised here "
            "for quick display. The authoritative, fully-cited score lives on "
            "the separate `eat:Score` node written via a prior POST /scores."
        ),
    )
    capacity_score: float = Field(
        ge=0, le=1, description="Same as urgency_score, but the capacity agent's score."
    )
    rationale_summary: str = Field(
        description=(
            "Short human-readable summary of why this referral is ranked "
            "here. NOT the full LLM-generated rationale (that's a separate, "
            "not-yet-built layer, product.md feature 9) -- this is the "
            "coordinator's own short note."
        ),
    )
    citations: list[DecisionCitationIn] = Field(
        min_length=1,
        description=(
            "Evidence for this specific ranked position. Must be non-empty -- "
            "`eat:cites` is 1..n on `eat:RankedPlacement` too (same rule as "
            "ScoreIn.citations); this is also what backs spec.md NFR2 (no "
            "placement is ever returned without evidence)."
        ),
    )
    rule_checks: list[RuleCheckIn] = Field(
        default_factory=list,
        description=(
            "CPC/CRT/ordering rule results for this position. Optional -- empty list is fine."
        ),
    )


class DecisionIn(BaseModel):
    """One coordinator decision: a full ranked list for one hospital, one
    day. Written atomically -- the decision, every ranking, its citations,
    and its rule checks all land in one Postgres transaction, then one
    graph-projection call (spec.md FR2)."""

    decision_id: str = Field(
        description=(
            "Caller-assigned unique ID for this decision (Postgres primary "
            "key). Distinct from the graph's Decision node IRI, which is "
            "keyed only by (hospital_hipe, as_of_date) -- namespaces.md's "
            "'one per hospital per day'."
        ),
        examples=["dec-run-2026-09-04-001-000001"],
    )
    run_id: str = Field(
        description=(
            "Same run_id as the scores this decision is built from -- ties "
            "the whole run's outputs together in one `run/{run_id}` named graph."
        ),
        examples=["run-2026-09-04-001"],
    )
    hospital_hipe: str = Field(
        min_length=4, max_length=4, description="4-character HIPE hospital code.", examples=["9001"]
    )
    as_of_date: date = Field(
        description=(
            "The day this ranking is for. Note: a second POST /decisions for "
            "the same (hospital_hipe, as_of_date) adds its placements to the "
            "same graph node rather than replacing it -- see GET /decisions'"
            " own description for what this means for reads."
        ),
    )
    coordinator_version: str = Field(
        description="Version string of the coordinating agent that produced this ranking."
    )
    rankings: list[RankingIn] = Field(
        min_length=1,
        description=(
            "The ranked list itself, one entry per referral -- order in this "
            "array doesn't matter, `position` is what determines rank. Must "
            "be non-empty; every `position` must be unique (enforced below)."
        ),
    )

    @field_validator("rankings")
    @classmethod
    def positions_unique(cls, rankings: list[RankingIn]) -> list[RankingIn]:
        # agent.decision_rankings UNIQUE dr_unique_position
        positions = [r.position for r in rankings]
        if len(positions) != len(set(positions)):
            raise ValueError("ranking positions must be unique within a decision")
        return rankings


class OverrideIn(BaseModel):
    """One clinician override of a ranked position -- an accept/reorder/
    override action, logged as a first-class event, never framed as a
    correction (product-guidelines.md)."""

    override_id: str = Field(
        description="Caller-assigned unique ID for this override (Postgres primary key)."
    )
    decision_id: str = Field(
        description=(
            "The decision this override applies to -- must already exist "
            "(written by a prior POST /decisions), or this request is "
            "rejected with 400. Its `as_of_date` is looked up server-side to "
            "build the graph IRI, so it isn't a separate field here."
        ),
    )
    hospital_hipe: str = Field(
        min_length=4, max_length=4, description="4-character HIPE hospital code.", examples=["9001"]
    )
    pathway_number: str = Field(
        description="The overridden referral's pathway number.", examples=["PW-9001-000007"]
    )
    clinician_id: str = Field(
        description=(
            "Identifies which clinician made this override -- attribution, "
            "not authentication (the bearer token itself carries no "
            "per-caller identity, spec.md NFR4)."
        ),
    )
    from_position: int | None = Field(
        default=None, description="The ranked position this referral moved from, if applicable."
    )
    to_position: int | None = Field(
        default=None, description="The ranked position this referral moved to, if applicable."
    )
    reason: str = Field(
        min_length=1,
        description=(
            "Why the clinician overrode the ranking. Must be non-blank -- "
            "'No override without one' (product-guidelines.md's rationale rules)."
        ),
    )
    rule_warning_accepted: bool = Field(
        default=False,
        description=(
            "Whether the clinician explicitly acknowledged a rule-violation "
            "warning (e.g. knowingly breaking RULE-ORDER) before submitting "
            "this override."
        ),
    )

    @field_validator("reason")
    @classmethod
    def reason_not_blank(cls, reason: str) -> str:
        # agent.overrides CHECK o_reason_not_blank (length(trim(reason)) > 0)
        if not reason.strip():
            raise ValueError("reason must not be blank")
        return reason


class NewPatientIn(BaseModel):
    """Demographics for a patient this hospital hasn't seen before (spec.md
    FR11). Only needed the first time a `patient_id` shows up at a given
    hospital -- a later referral for the same (hospital_hipe, patient_id)
    omits this entirely and just reuses the existing patient record."""

    patient_sex: Sex = Field(description="M/F/U, this hospital's own record for this patient.")
    patient_date_of_birth: date = Field(description="As held by this hospital's own record.")
    area_of_residence_code: str = Field(
        min_length=4, max_length=4, description="4-character area-of-residence code."
    )
    ihi_number: str | None = Field(
        default=None,
        description=(
            "National identifier, if known -- around a third of real patients have "
            "none (core.patients.ihi_number's own comment), so this is optional. "
            "When given, `person_sex`/`person_date_of_birth`/`person_area_of_residence_code` "
            "become required too, to create the linked core.persons/eat:Person record."
        ),
    )
    person_sex: Sex | None = Field(
        default=None, description="Required if ihi_number is given -- the national record's sex."
    )
    person_date_of_birth: date | None = Field(
        default=None, description="Required if ihi_number is given."
    )
    person_area_of_residence_code: str | None = Field(
        default=None,
        min_length=4,
        max_length=4,
        description="Required if ihi_number is given -- may differ from the hospital record's.",
    )

    @model_validator(mode="after")
    def person_fields_required_with_ihi(self) -> NewPatientIn:
        if self.ihi_number is not None and (
            self.person_sex is None
            or self.person_date_of_birth is None
            or self.person_area_of_residence_code is None
        ):
            raise ValueError(
                "person_sex, person_date_of_birth and person_area_of_residence_code are "
                "required when ihi_number is given"
            )
        return self


class ReferralIn(BaseModel):
    """A brand-new referral arriving at a hospital -- spec.md FR11 (user
    request: "input new patients"). Writes `core.patients`/`core.persons`
    (only if `new_patient` is given), `core.referrals`, and today's initial
    `core.referral_daily` row (triage_status='awaiting_triage', wait
    counters computed fresh), then projects `eat:Referral` (+ `eat:Patient`/
    `eat:Person` if new, + an initial `eat:ReferralState`) into the graph's
    `inputs` named graph -- the same graph the batch mapping pipeline
    projects into, so this referral is indistinguishable from a
    batch-loaded one to every other read endpoint once written.

    This is data intake only -- it does NOT recompute any agent score or
    re-run the coordinator's ranking. That is deliberate: scoring and
    ranking are judgement calls belonging to the urgency/capacity/
    coordinator agents (a separate track), not something this data-access
    service decides on its own. An agent (or orchestrator) watching for new
    referrals is expected to call `POST /scores` and `POST /decisions`
    itself once it has judged this referral, the same way it already would
    for any other referral in the cohort."""

    hospital_hipe: str = Field(
        min_length=4, max_length=4, description="4-character HIPE hospital code.", examples=["9001"]
    )
    patient_id: str = Field(
        description=(
            "This hospital's own patient identifier -- always required, whether the "
            "patient is new (pair with `new_patient`) or already known to this hospital."
        ),
        examples=["P-90010001"],
    )
    new_patient: NewPatientIn | None = Field(
        default=None,
        description=(
            "Demographics for this patient, if `patient_id` is new to this hospital. "
            "Omit when the patient already has a core.patients row here -- the referral "
            "attaches to the existing record. If omitted and the patient truly doesn't "
            "exist yet, the request is rejected with 400."
        ),
    )
    specialty_hipe: str = Field(
        min_length=4,
        max_length=4,
        description="4-character HIPE specialty code -- must be active at this hospital.",
        examples=["0100"],
    )
    referral_date: date = Field(description="Date on the GP's referral letter.")
    referral_received_date: date = Field(
        description="Date the hospital received it -- must be >= referral_date."
    )
    priority_level_gp: int | None = Field(
        default=None,
        description="Optional GP-assigned priority (1 or 2), coded via core.ref_codes.",
    )
    referral_source: int = Field(
        description=(
            "Where the referral came from, coded via core.ref_codes (referral_source table)."
        )
    )
    high_clinical_or_social_needs: bool = Field(
        default=False,
        description="Whether this referral is flagged for high clinical/social needs.",
    )
